version: "3.7"
services:
  mobileapps:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 8888:8888
    volumes:
    - .:/srv/service
    - /srv/service/node_modules
  pagelib:
    build:
      context: ./pagelib
      dockerfile: Dockerfile.dev
    volumes:
    - ./pagelib:/srv/app
    - /srv/app/node_modules
