version: 1.0
variants:
    dev:
        services:
            mobileapps:
                ports:
                    - "8888:8888"
            pagelib:
                path: pagelib
    build:
        services:
            pagelib:
                blubber:
                    variant: dev
                path: pagelib
                entrypoint: npm run build
